version: '3.8'

services:
  vista:
    image: minio/minio:RELEASE.2024-10-29T16-01-48Z-cpuv1
    container_name: vista
    networks:
      stelar_net:
        ipv4_address: 172.10.0.10
    volumes:
      - ./vista/minio/data:/minio/data
    environment:
      MINIO_ROOT_USER: ${VISTA_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${VISTA_ROOT_PASSWORD}
      MINIO_BROWSER_REDIRECT_URL: https://console-s3-vista.stelar.gr/
    command: server --console-address ":9001" /minio/data
    restart: always
    expose:
      - 9000
      - 9001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://172.10.0.10:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
    mem_limit: 12g             
    cpus: 4                   

  abaco:
    image: minio/minio:RELEASE.2024-10-29T16-01-48Z-cpuv1
    container_name: abaco
    networks:
      stelar_net:
        ipv4_address: 172.10.0.20
    volumes:
      - ./abaco/minio/data:/minio/data
    environment:
      MINIO_ROOT_USER: ${ABACO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${ABACO_ROOT_PASSWORD}
      MINIO_BROWSER_REDIRECT_URL: https://console-s3-abaco.stelar.gr/
    command: server --console-address ":9001" /minio/data
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://172.10.0.20:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
    mem_limit: 12g             
    cpus: 4              

  ak:
    image: minio/minio:RELEASE.2024-10-29T16-01-48Z-cpuv1
    container_name: ak
    networks:
      stelar_net:
        ipv4_address: 172.10.0.30
    volumes:
      - ./ak/minio/data:/minio/data
    environment:
      MINIO_ROOT_USER: ${AK_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${AK_ROOT_PASSWORD}
      MINIO_BROWSER_REDIRECT_URL: https://console-s3-ak.stelar.gr/
    command: server --console-address ":9001" /minio/data
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://172.10.0.30:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
    mem_limit: 12g            
    cpus: 4                   

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    networks:
      stelar_net:
        ipv4_address: 172.10.0.100
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/certs:ro
    depends_on:
      - vista
      - abaco
      - ak
    ports:
      - "80:443"
      - "443:443"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    mem_limit: 8g             
    cpus: 4                    

networks:
  stelar_net:
    ipam:
      driver: default
      config:
        - subnet: 172.10.0.0/24